### PR TITLE
testing

### PR DESCRIPTION
**Pull request by EmanuelBurgess**
Please review my code.

### CODE REVIEW

**Review by hazem94 — CHANGES_REQUESTED** [review]
#!/bin/bash

**Review by EmanuelBurgess — COMMENTED** [review]
Please review the updates that I made

**Review by hazem94 — CHANGES_REQUESTED** [review]
Aws s3 ls

**Review by EmanuelBurgess — COMMENTED** [review]
Please review

**Review by hazem94 — APPROVED** [review]
LGTM 👌

**Pull request merged**
